services:
  frontend:
    build:
      context: ./FRONT
    ports:
      - "80:4200"  
    depends_on:
      - api  
    networks:
      - heart_network  

  api:
    build:
      context: ./API
    ports:
      - "3001:3001"  
    networks:
      - heart_network  

networks:
  heart_network:
    driver: bridge  
